map/urls.py
from . import views
from django.urls import path
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'map'
urlpatterns = [
    path('', views.index, name='index'),
    path('show-summary/<int:id>/', views.show_op, name='show_op'),
    # path('show-image/<int:id>/', views.show_image, name='show_img'),
    


]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('map.urls',namespace='steg')),
    path("admin/", admin.site.urls),
]

map/models.py
from django.db import models
# from django.contrib.postgres.fields import ArrayField
# Create your models here.

class User(models.Model):
    id = models.AutoField(primary_key=True)
    inputAudioPath = models.FileField(upload_to='audio/', null=False, verbose_name="", default="test.waf")
    outputSummary = models.TextField(default="")
    outputKeywords = models.TextField(default="")
    outputLinks = models.TextField(default="")


    def __str__(self):
        return str(self.inputAudioPath) + " ID : " + str(self.id)
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('map:show_op', kwargs={'id': self.id})

map/forms.py
from django import forms

from map.models import User

class AudioForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["inputAudioPath"]

map/views.py
from asyncio.windows_events import NULL
from django.urls import reverse
from django.shortcuts import redirect, render
import ast
# Create your views here.

from django.http import HttpResponse

from numpy import imag

# from sympy import re
from .models import User
from .forms import AudioForm
from algo.test import testing
import algo.audioextraction.main as al

import algo.audioextraction.audiosplit as asp
import algo.audioextraction.audioext as ae
import algo.audioextraction.summarizer as sm
from django.template.response import TemplateResponse


def index(request):
    user_model = NULL
    form = AudioForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        user_model = form.save(commit=True)
        audio_path = user_model.inputAudioPath
        user_id = user_model.id
        audio_path = "media/"+str(audio_path)
        # output = al.map(str(audio_path))
        al.aud_split(audio_path)
        final_speech = al.transcription(audio_path)
        links = al.key_ext_link_rec(audio_path)
        summary = al.summarizer(audio_path)
        links[1] = links[1].split("\n")
        user_model.outputSummary = summary
        user_model.outputKeywords = links[0]
        user_model.outputLinks = links[1]

        user_model.save()
        return redirect(user_model)

    context = {
        'form': form
    }

    return render(request, 'map/index.html', context)


def show_op(request, id):
    user = User.objects.filter(id=id).first()
    # context = {
    #     'output' : user.o
    # }

    hyperLinks = ast.literal_eval(user.outputLinks)[1:]

    if user:
        return render(request, 'map/show_op.html', {
            'user': user,
            'hyperLinks': hyperLinks,
        })
    return

templates/map/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'map/styles.css' %}" />
    <title>MAP Lecture Summariser</title>

</head>
<body>
    <div class="topnav">
        <a class="active" href="#home">Home</a>
        
        <a href="#about">About</a>
    </div>
    <br>  
    <div style="margin: 5%;">
    <h1>WELCOME TO MAP LECTURE SUMMARIZER!</h1>
    <p>Upload your lecture audios, and get a concise summary of it with important keywords and useful online resource links with just a click of a button :)</p>
    
    <br><br>
    <h2>Upload any audio of your choice!</h2><br>
    <form enctype="multipart/form-data" method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
    
        <input type="submit" class="button-1" role="button" value="Upload" />
    </form>
    </div>
    <div class="footer" style="margin: -0.1%;">
        <p style="text-align: centre;" id="about">Made by Annant Maheshwari, Malvika Koushik and Poorna Hegde.</p>
    </div>
</body>
</html>

templates/map/show_op.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'map/styles.css' %}" />

    <title>MAP Lecture Summariser</title>
</head>

<body>
    <div class="topnav">
        <a class="active" href="{% url 'map:index' %}">Home</a>
        
        <a href="#about">About</a>
    </div>
        
        <div style="margin: 5%;">
        <h1>Here you go! :)</h1>
    {% load static %}
    <h2>SUMMARY</h2>
    {{ user.outputSummary }}
    <br>
    
    <!-- {{ links }} -->
    <h2> LINKS </h2>
    <ul>
        {% for link in hyperLinks %}
        <a href="{{ link }}" target="_blank">{{ link }}</a> <br>
        {% endfor %}
    </ul>
    
    <h2>KEYWORDS</h2>
    {{ user.outputKeywords }}
    <br>
    </div>
    
</body>

</html>